DEF_SREG(IP,   "ip",    0)
DEF_SREG(SP,   "sp",    1)
DEF_SREG(STAT, "stat",  2)
DEF_SREG(IENB, "ienb",  3)
DEF_SREG(IWRK, "iwrk",  4)
DEF_SREG(TCNT, "tcnt",  5)
DEF_SREG(TCTR, "tctr",  6)
DEF_SREG(TCMP, "tcmp",  7)