DEF_INSTR(End,              "end"   )
DEF_INSTR(Ret,              "ret"   )
DEF_INSTR(Iret,             "iret"  )
DEF_INSTR(Rst,              "rst"   )
DEF_INSTR(Nop,              "nop"   )
DEF_INSTR(Add,              "add"   )
DEF_INSTR(Sub,              "sub"   )
DEF_INSTR(Mul,              "mul"   )
DEF_INSTR(Rot,              "rot"   )
DEF_INSTR(Sh,               "sh"    )
DEF_INSTR(And,              "and"   )
DEF_INSTR(Or,               "or"    )
DEF_INSTR(Xor,              "xor"   )
DEF_INSTR(Not,              "not"   )
DEF_INSTR(Mov,              "mov"   )
DEF_INSTR(Straml,           "straml")
DEF_INSTR(Ldraml,           "ldraml")
DEF_INSTR(Stramh,           "stramh")
DEF_INSTR(Ldramh,           "ldramh")
DEF_INSTR(Stsprd,           "stsprd")
DEF_INSTR(Ldsprd,           "ldsprd")
DEF_INSTR(Clr,              "clr"   ) 
DEF_INSTR(Movll,            "movll" )
DEF_INSTR(Movlh,            "movlh" )
DEF_INSTR(Movhl,            "movhl" )
DEF_INSTR(Movhh,            "movhh" )
DEF_INSTR(Movl,             "movl"  )
DEF_INSTR(Movh,             "movh"  )
DEF_INSTR(Movd,             "movd"  )
DEF_INSTR(Addb,             "addb"  )
DEF_INSTR(Subb,             "subb"  )
DEF_INSTR(Mulb,             "mulb"  )
DEF_INSTR(Shl,              "shl"   )
DEF_INSTR(Shr,              "shr"   )
DEF_INSTR(Rol,              "rol"   )
DEF_INSTR(Ror,              "ror"   )
DEF_INSTR(Pushh,            "pushh" )
DEF_INSTR(Poph,             "poph"  )
DEF_INSTR(Pushl,            "pushl" )
DEF_INSTR(Popl,             "popl"  )
DEF_INSTR(Out,              "out"   )
DEF_INSTR(In,               "in"    )
DEF_INSTR(Neg,              "neg"   )
DEF_INSTR(Call,             "call"  )
DEF_INSTR(Jmp,              "jmp"   )
DEF_INSTR(Jez,              "jez"   )
DEF_INSTR(Jnz,              "jnz"   )
DEF_INSTR(Jaz,              "jaz"   )
DEF_INSTR(Jbz,              "jbz"   )
DEF_INSTR(Jaez,             "jaez"  )
DEF_INSTR(Jbez,             "jbez"  )