all:
	@g++ -std=gnu++11 -g main.cpp -Wall -Wcast-qual -Wcast-align \
	-Wwrite-strings -Winline -Wredundant-decls -Wpointer-arith \
	-o ./Assembler

build:
	@g++ -std=gnu++11 -g main.cpp -Wall -Wcast-qual -Wcast-align \
	-Wwrite-strings -Winline -Wredundant-decls -Wpointer-arith \
	-o ./Assembler

clean:
	@rm -rf *.o Assembler